update littlesis bash script for prod

diff --git a/littlesis b/littlesis
--- a/littlesis
+++ b/littlesis
@@ -142,14 +142,12 @@ setup_database() {
 }
 
 
-
-
 nginx_logs() {
     if [ "$1" == "access" ] || [ "$1" == "error" ]; then
-	    local log_file="/var/log/nginx/${1}.log"
-	    $docker_compose exec nginx /bin/sh -c "tail -f ${log_file}"
+        local log_file="/var/log/nginx/${1}.log"
+        $docker_compose exec nginx /bin/sh -c "tail -f ${log_file}"
     else
-	    fail 'There are only two nginx logs available: access and error'
+fail 'There are only two nginx logs available: access and error'
     fi
 }
 
@@ -157,11 +155,11 @@ rails_coverage() {
     local cov_file=file://$rails_repo/coverage/index.html
 
     if [ -x "$(command -v chromium)" ];then
-	    chromium --new-window $cov_file > /dev/null 2>&1
+        chromium --new-window $cov_file > /dev/null 2>&1
     elif [ -x "$(command -v firefox)" ];then
-	    firefox --new-window $cov_file > /dev/null 2>&1
+        firefox --new-window $cov_file > /dev/null 2>&1
     else
-	    fail 'Could not find firefox or chromium'
+        fail 'Could not find firefox or chromium'
     fi
 }
 
@@ -180,7 +178,19 @@ littlesis_fetch_pull_request() {
 }
 
 littlesis_status() {
-    if ! [ "$rails_env" == "production" ];then
+    local rails_git_commit=$(cd $rails_repo && git rev-parse --short HEAD)
+    local rails_git_branch=$(cd $rails_repo && git rev-parse --abbrev-ref HEAD)
+
+    echo "On Rails commit $rails_git_commit on branch $rails_git_branch"
+
+    if [ "$rails_env" == "production" ]
+    then
+        if systemctl is-active -q littlesis;then
+            echo "littlesis.service is active"
+        else
+            fail "littlesis.service is not active"
+        fi
+    else
         local services_running="$($docker_compose ps --services --filter "status=running" | sed '/^$/d' | wc -l)"
 
         if [ "$services_running" == '4' ];then
@@ -190,10 +200,7 @@ littlesis_status() {
         fi
     fi
 
-    local rails_git_commit=$(cd $rails_repo && git rev-parse --short HEAD)
-    local rails_git_branch=$(cd $rails_repo && git rev-parse --abbrev-ref HEAD)
 
-    echo "On Rails commit $rails_git_commit on branch $rails_git_branch"
 }
 
 littlesis_docker_build() {
@@ -220,7 +227,7 @@ web_app_exec() {
 }
 
 bundle_exec() {
-    web_app_exec $bundle_path exec "$@"
+    web_app_exec "$bundle_path" exec "$@"
 }
 
 run_postgres_cmd() {
@@ -250,15 +257,15 @@ deploy() {
 
 case $1 in
     docker|docker_compose|docker-compose)
-	    shift
+        shift
         $docker_compose "$@"
-	    ;;
+        ;;
     up)
-	    $docker_compose up -d
-	    ;;
+        $docker_compose up -d
+        ;;
     down)
-	    $docker_compose down
-	    ;;
+        $docker_compose down
+        ;;
     delete)
         $docker_compose down -v
         ;;
@@ -276,17 +283,18 @@ case $1 in
         bundle_exec pumactl -p tmp/puma.pid "$@"
         ;;
     test|rspec)
-	    shift
+        shift
         set_environment_to_test
-	    bundle_exec rspec "$@"
-	    ;;
+        bundle_exec rspec "$@"
+        ;;
     cmd)
-	    shift
+        shift
         web_app_exec "$@"
-	    ;;
+        ;;
     bundle)
-	    web_app_exec "$@"
-	    ;;
+        shift
+        bundle_exec "$@"
+        ;;
     yarn)
         shift
         bundle_exec bin/yarn "$@"
@@ -339,11 +347,11 @@ case $1 in
                 ;;
             nginx)
                 if test "$2" = "error"; then
-	                nginx_logs error
+                    nginx_logs error
                 else
                     nginx_logs access
                 fi
-	            ;;
+                ;;
             docker)
                 $docker_compose logs --follow
                 ;;
@@ -354,22 +362,22 @@ case $1 in
         ;;
     reset-test-db)
         set_environment_to_test
-	    bundle_exec rake db:reset
-	    ;;
+        bundle_exec rake db:reset
+        ;;
     data)
         shift
         bundle_exec rails runner lib/scripts/data.rb -- "$@"
         ;;
     search|rg)
-	    shift
-	    cd rails && rg "$*"
-	    ;;
+        shift
+        cd rails && rg "$*"
+        ;;
     cov|coverage)
-	    rails_coverage
-	    ;;
+        rails_coverage
+        ;;
     redis)
         redis_cli
-	    ;;
+        ;;
     fec)
         shift
         bundle_exec rails runner lib/scripts/fec "$@"
@@ -383,7 +391,9 @@ case $1 in
         clone_repo
         ;;
     setup-database)
-        setup_database
+        if ! [ "$rails_env" == "production" ];then
+            setup_database
+        fi
         ;;
     run-sql)
         shift
@@ -396,12 +406,12 @@ case $1 in
         web_app_exec /bin/bash --login
         ;;
     -h|help|--help)
-	    show_help
-	    ;;
+        show_help
+        ;;
     ?*) # End of all options.
         fail "Invalid option"
-	    ;;
+        ;;
     *)
-	    short_help
-	    ;;
+        short_help
+        ;;
 esac
